[package]
name = "netzero"
version = "0.1.0"
authors = ["Robert Morrison <robbieguy98@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "2.0"
clap = "2.33"
time = "0.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
serde_json = "1.0"
crossbeam = "0.7"
console = "0.11"
